name: trenda
description: "Trenda marketplace"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_login_facebook: ^1.6.2
  pin_code_fields: ^8.0.1
  country_pickers: ^2.0.0
  sms_autofill: ^2.3.0
  intl: ^0.18.0
  dio: ^5.4.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_onboarding_slider: ^1.0.11
  flutter_easyloading: ^3.0.5
  carousel_slider: ^4.2.1
  flutter_carousel_widget: ^2.2.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/img_onboarding_1_.png
    - assets/images/img_onboarding_2_.png
    - assets/images/img_onboarding_3._png
  fonts:
    - family: Gilroy-Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
    - family: Gilroy-Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 400
    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 400
    - family: Gilroy-ExtraBold
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 400
    - family: Gilroy-Semi-Bold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 400
